---
# Copyright: (c) 2022, XLAB Steampunk <steampunk@xlab.si>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Show a Deprecation warning message
- name: Deprecation warning
  fail:
    msg: "Warning!!! configure_aio_server role is deprecated"
  when: not ansible_check_mode
  failed_when: false

- name: Update config files and restart FDO AIO service
  block:
    - name: Create backups of old config files and create new ones from templates
      ansible.builtin.import_tasks: copy_config_files.yml

    - name: Restart FDO AIO Service
      ansible.builtin.systemd:
        name: fdo-aio
        state: restarted
        enabled: true

    - name: Check FDO AIO Service Status
      ansible.builtin.systemd:
        name: fdo-aio
      register: service_fdo_aio_status

    - name: Report Status of FDO AIO Service
      ansible.builtin.fail:
        msg: FDO AIO Service failed to restart after configuration change.
      when: service_fdo_aio_status.status.ActiveState != 'active'

    - name: Open Required Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - "{{ aio_configuration_listen_port_manufacturing_server }}/tcp"
        - "{{ aio_configuration_listen_port_owner_onboarding_server }}/tcp"
        - "{{ aio_configuration_listen_port_rendezvous_server }}/tcp"
        - "{{ aio_configuration_listen_port_serviceinfo_api_server }}/tcp"

  rescue:
    - name: Reset config files
      ansible.builtin.import_tasks: reset_config_files.yml
      when: enable_roll_back | bool

    - name: Restart FDO AIO Service
      ansible.builtin.systemd:
        name: fdo-aio
        state: restarted
        enabled: true
      when: enable_roll_back | bool

    - name: FDO AIO Service configuration failed
      ansible.builtin.fail:
        msg: FDO AIO Service configuration failed.
